apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
  labels:
    app: my-app   # Adăugarea label-ului pentru selectorul din serviciu
spec:
  containers:
    - name: my-app-container
      image: nickxo/laborator2_image:latest
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app   # Selectorul trebuie să fie compatibil cu label-ul din pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
